#!/bin/bash

files=(hetList.v
       tactics.v
       ast.v
       heap.v
       semantics.v
       stepPreservesRewind.v
       partialImpliesFull.v
	   fullImpliesPartial.v
	partialEqFull.v
       )

if [[ $* == *-clean* ]]; then
	rm *.glob
	rm *.vo
	exit 
fi

#Print out file numbers
if [[ $* == *-p* ]]; then
    COUNTER=0
    for i in "${files[@]}"
    do
        echo "$COUNTER: $i"
        let COUNTER=COUNTER+1 
    done
    exit
fi


#Start building at a particular file number
if [ "$#" -ne 1 ]; then
    COUNTER=1
    for i in "${files[@]}"
    do
        echo "working on $i (file $COUNTER of ${#files[@]})"
        coqc $i
        let COUNTER=COUNTER+1 
    done


else
    n=${#files[@]}
    for (( c=$1; c<n; c++ ))
    do
       let counter=c+1
       echo "working on ${files[c]} (file $counter of $n)"
       coqc ${files[c]}
    done
fi

    

    





